#!/usr/bin/env -S uv run python
# -*- mode: python -*-
import sys, os
sys.path[0] = os.path.dirname(sys.path[0]) if sys.path[0] else os.getcwd()
import sys, socket, numpy as np, tact

#env = tact.Env('demos/obj1', render=True, redraw=4)
env = tact.Env('demos/obj2', render=True, redraw=4)

#env = tact.Env('demos/box_wall', render=True, redraw=16)
#env = tact.Env('demos/min_test', render=True, redraw=16)   # 'solver: minimal' test: sphere on z=0 ground, ball given +x qd0=0.1 m/s

#env = tact.Env('demos/arm2', render=True)
#env = tact.Env('demos/arm2', offset=[0, 1, 0, 0, 0, 0], q0=[-90, 0], render=True, sleep=0.01, redraw=1); env.add('demos/arm2', offset=[0.1, 1, 0, 0, 0, 0], q0=[-45, 0])

#env = tact.Env('demos/arm3', render=True, sleep=0.01)
#env = tact.Env('demos/arm4', render=True, sleep=0.01)

#env = tact.Env('demos/fv', render=True)
#env = tact.Env('demos/cartpole', q0=[0, 45], render=True)


#pull = zmq.Context().socket(zmq.PULL)
#pull.bind('ipc:///dev/shm/zmq-pp0')
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('0.0.0.0', 6600))
sock.setblocking(False)


mode = [0]*len(env.q) #set all joint torque mode
cnt = 0

def msgproc(msg):
    global cnt
    w = msg.split()
    if w[0] == 'quit': env.finish(); exit(0)
    elif w[0] == 'reset': env.reset(); cnt = 0

    
while True:
    #try: msg = pull.recv(flags=zmq.NOBLOCK)
    #except zmq.ZMQError: pass
    #else: msgproc(msg); continue
    try: msg, clnt_addr = sock.recvfrom(1024)
    except BlockingIOError: pass
    else: msgproc(msg.decode()); continue
    
    u = np.zeros(env.dof)
    y = env.step(u)
    
    #if len(y) > 0: print(cnt, y)
    #else: print(cnt)
    
    cnt += 1

    #if cnt == 100: break
