#!/usr/bin/env -S uv run python
# -*- mode: python -*-
import sys, os
sys.path[0] = os.path.dirname(sys.path[0]) if sys.path[0] else os.getcwd()
import socket, numpy as np, tact

def scene_path(name):
    if os.path.isabs(name) or os.path.exists(name) or os.path.exists(name + '.yml'):
        return name
    for subdir in ('demos', 'envs'):
        path = os.path.join(tact.pkg_dir, subdir, name)
        if os.path.exists(path + '.yml'):
            return path
    return name

scene = scene_path(sys.argv[1] if len(sys.argv) > 1 else 'obj2')
env = tact.Env(scene, render=True, redraw=4)

# Examples:
#   ./yml-test obj1
#   ./yml-test box_wall
#   ./yml-test min_test
#   ./yml-test arm2
#   ./yml-test hf1


#pull = zmq.Context().socket(zmq.PULL)
#pull.bind('ipc:///dev/shm/zmq-pp0')
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
sock.bind(('0.0.0.0', 6600))
sock.setblocking(False)


mode = [0]*len(env.q) #set all joint torque mode
cnt = 0

def msgproc(msg):
    global cnt
    w = msg.split()
    if not w: return
    if w[0] == 'quit': env.finish(); exit(0)
    elif w[0] == 'reset': env.reset(); cnt = 0

    
while True:
    #try: msg = pull.recv(flags=zmq.NOBLOCK)
    #except zmq.ZMQError: pass
    #else: msgproc(msg); continue
    try: msg, clnt_addr = sock.recvfrom(1024)
    except BlockingIOError: pass
    else: msgproc(msg.decode()); continue
    
    u = np.zeros(env.dof)
    y = env.step(u)
    
    #if len(y) > 0: print(cnt, y)
    #else: print(cnt)
    
    cnt += 1

    #if cnt == 100: break
