#!/usr/bin/env python3
import ctypes, zmq, numpy as np, tact, rb10

#env = tact.sim('rb10', render=True)
env = ctypes.CDLL('../../mujoco/mujoco.io'); n_y = env.init('/home/ubuntu/fgx/mujoco/models/rb10/rb10.xml'.encode(), 16, 5)
#env = ctypes.CDLL('./chrono.so'); n_y = env.init(16, 0, 0) #render, env, tool
#env = ctypes.CDLL('./io.so'); n_y = env.init('no_option'.encode())

pull = zmq.Context().socket(zmq.PULL)
pull.bind('ipc:///tmp/zmq')
cnt = 0


def raycast(pos_x, pos_y, pos_z, dir_x, dir_y, dir_z):
    env.raycast.restype = ctypes.c_double
    dist = env.raycast(ctypes.c_double(pos_x), ctypes.c_double(pos_y), ctypes.c_double(pos_z), ctypes.c_double(dir_x), ctypes.c_double(dir_y), ctypes.c_double(dir_z)) 


def scan3(x, y, z, roll, pitch, yaw):
    L = np.zeros(1024*3)
    _L = (ctypes.c_double*len(L))(*L)
    
    n = env.scan3(ctypes.c_double(x), ctypes.c_double(y), ctypes.c_double(z), ctypes.c_double(roll), ctypes.c_double(pitch), ctypes.c_double(yaw), _L)
    p = np.array(_L)
    pc = []
    
    for i in range(n): pc.append([p[3*i+0], p[3*i+1], p[3*i+2]])
    return pc

    #msg = ''
    #for i in range(21*21*3): msg += ' %f' %pc[i]
    #print(msg)

    
def step(u):
    y = np.zeros(n_y)
    _u = (ctypes.c_double*len(u))(*u)
    _y = (ctypes.c_double*len(y))(*y)
    env.step(_u, _y)
    return np.array(_y)


def msgproc(msg):
    global cnt
    w = msg.decode().split()
    if w[0] == 'quit': env.finish(); exit(0)
    elif w[0] == 'reset': env.reset(); cnt = 0
    else: agent.msgproc(w)

    
while True:
    try: msg = pull.recv(flags=zmq.NOBLOCK)
    except zmq.ZMQError: pass
    else: msgproc(msg); continue

    if cnt == 0:
        agent = rb10.agent(env)
        u = np.zeros(6)
        
    if type(env) == ctypes.CDLL: y = step(u)
    else: y = env.step(u)

    if cnt % 1000 == 0:
        #if type(env) == ctypes.CDLL: dist = raycast(0, 0, 5, 0, 0, -1)
        #else: dist = env.raycast(0, 0, 5, 0, 0, -1)
        #print(dist)
        
        if type(env) == ctypes.CDLL: pc = [] # scan3(0, 0, 2, 0, np.pi/2, 0)
        else: pc = env.scan3(0, 0, 2, 0, np.pi/2, 0)

        msg = 'pc'
        for i in range(len(pc)): msg += ' %f %f %f' %(pc[i][0], pc[i][1], pc[i][2])
        print(msg)
        
    u = agent.update(y)
    cnt += 1
