#!/usr/bin/env python3
import time, numpy as np, tact

#m = tact.model('arm2')
#m = tact.model('arm4')
#m = tact.model('rb5/rb5')
m = tact.model('../dog/dog')
#m = tact.model('../zen/zen')

q = np.zeros(len(m.m))
qd = np.zeros(len(m.m))
tau = np.zeros(len(m.m))
f_ext = np.zeros((len(m.m), 6))

t1 = time.time()

for i in range(1000):
    qdd = tact.ab_featherstone(m.X, m.I6, m.parent, m.jtype, q, qd, tau, f_ext, m.g)

    #T = tact._fk(m.Ti, m.parent, m.jtype, q)
    #f_ext = tact.contact_ccd(T, m.parent, m.jtype, m.convex, qd)
    #f_ext = tact.contact_ground_sphere(T, m.parent, m.jtype, m.convex, qd)
    
t2 = time.time()
print(t2 - t1)
